//
//  PaintCodeTutorial.h
//  PaintCodeTutorial
//
//  Created by hongyu_zhao on 16/9/4.
//  Copyright (c) 2016 hongyu_zhao. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeTutorial : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* stopwatchTargets;

// Colors
+ (UIColor*)baseColor;

// Drawing Methods
+ (void)drawStopwatch;
+ (void)drawStopWatch_Hand;

// Generated Images
+ (UIImage*)imageOfStopwatch;

@end
